apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    run: web
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 9000
    protocol: TCP
    name: web-tcp
  selector:
    run: web
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  template:
    metadata:
      labels:
        run: web
    spec:
      containers:
      - name: web
        image: eu.gcr.io/potato-169306/workshopkubernetes_web
        ports:
        - containerPort: 9000
        env:
        - name: REDIS_HOST
          value: redis.default.svc.cluster.local
